//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicensePlateRecognition
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesLicence
    {
        public int id { get; set; }
        public string localRoute { get; set; }
        public string name { get; set; }
        public string carLicence { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
    }
}
